flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- RSA-2.2.0
- SHA-1.6.4.2
- adjunctions-4.3
- aeson-1.0.2.1
- ansi-terminal-0.6.2.3
- asn1-encoding-0.9.4
- asn1-parse-0.9.4
- asn1-types-0.3.2
- attoparsec-0.13.1.0
- authenticate-oauth-1.5.1.2
- base-compat-0.9.1
- base-orphans-0.5.4
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- bifunctors-5.4.1
- blaze-builder-0.4.0.2
- byteable-0.1.1
- call-stack-0.1.0
- cereal-0.5.4.0
- comonad-5
- connection-0.2.6
- contravariant-1.4
- cookie-0.4.2.1
- crypto-api-0.13.2
- crypto-pubkey-types-0.4.3
- cryptohash-0.11.9
- cryptonite-0.21
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.5.0.2
- dlist-0.8.0.2
- entropy-0.3.7
- exceptions-0.8.3
- foundation-0.0.2
- free-4.12.4
- hourglass-0.2.10
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- http-client-0.4.31.2
- http-client-tls-0.2.4.1
- http-types-0.9.1
- kan-extensions-5.0.1
- lens-4.15.1
- lens-aeson-1.0.0.5
- memory-0.14
- mime-types-0.1.0.7
- old-locale-1.0.0.7
- pem-0.2.2
- prelude-extras-0.4.0.3
- profunctors-5.2
- psqueues-0.2.2.3
- pureMD5-2.1.3
- quickcheck-io-0.1.4
- reflection-2.1.2
- scientific-0.3.4.9
- semigroupoids-5.1
- semigroups-0.18.2
- setenv-0.1.1.3
- socks-0.5.5
- streaming-commons-0.1.16
- tagged-0.8.5
- time-locale-compat-0.1.1.3
- tls-1.3.9
- transformers-compat-0.5.1.4
- void-0.7.1
- wreq-0.4.1.0
- x509-1.6.5
- x509-store-1.6.2
- x509-system-1.6.4
- x509-validation-1.6.5
resolver: ghc-8.0.1
