flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.0.2.1
- cryptonite-0.21
- foundation-0.0.2
- hjsonpointer-1.1.0.0
- hjsonschema-1.3.0.0
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- lens-4.15.1
- memory-0.14
- tls-1.3.9
resolver: lts-7.14
